Homework 6
================
Pooja Mukund
11/26/2021

``` r
#Load relevant libraries

library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.5     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(viridis)
```

    ## Loading required package: viridisLite

``` r
#Setup for visualizations
knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%"
)
```

## Load Data

``` r
birth<- read_csv("data/birthweight.csv")
```

    ## Rows: 4342 Columns: 20

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Data Cleaning

First we will check if there are any NAs in columns

``` r
# Check for NAs 
birth%>%
summarise_all(funs(sum(is.na(.)))) # No NAs in columns 
```

    ## Warning: `funs()` was deprecated in dplyr 0.8.0.
    ## Please use a list of either functions or lambdas: 
    ## 
    ##   # Simple named list: 
    ##   list(mean = mean, median = median)
    ## 
    ##   # Auto named with `tibble::lst()`: 
    ##   tibble::lst(mean, median)
    ## 
    ##   # Using lambdas
    ##   list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

    ## # A tibble: 1 × 20
    ##   babysex bhead blength   bwt delwt fincome frace gaweeks malform menarche
    ##     <int> <int>   <int> <int> <int>   <int> <int>   <int>   <int>    <int>
    ## 1       0     0       0     0     0       0     0       0       0        0
    ## # … with 10 more variables: mheight <int>, momage <int>, mrace <int>,
    ## #   parity <int>, pnumlbw <int>, pnumsga <int>, ppbmi <int>, ppwt <int>,
    ## #   smoken <int>, wtgain <int>

From the data description in homework assignment we know that `babysex`,
`frace`, `malform`, `mrace` are all categorical variables that are
currently coded numerically. We will first change this to categorical
variables.

``` r
birth%>%
  summarise_all(class)
```

    ## # A tibble: 1 × 20
    ##   babysex bhead   blength bwt     delwt   fincome frace gaweeks malform menarche
    ##   <chr>   <chr>   <chr>   <chr>   <chr>   <chr>   <chr> <chr>   <chr>   <chr>   
    ## 1 numeric numeric numeric numeric numeric numeric nume… numeric numeric numeric 
    ## # … with 10 more variables: mheight <chr>, momage <chr>, mrace <chr>,
    ## #   parity <chr>, pnumlbw <chr>, pnumsga <chr>, ppbmi <chr>, ppwt <chr>,
    ## #   smoken <chr>, wtgain <chr>

``` r
#All coded numerically 

birth%>%
  distinct(frace)
```

    ## # A tibble: 5 × 1
    ##   frace
    ##   <dbl>
    ## 1     1
    ## 2     2
    ## 3     3
    ## 4     4
    ## 5     8

``` r
#Only 5 categories - 1, 2, 3, 4, 8 even though description has 9 there are no 9s that exist in this current dataset 

birth%>%
  distinct(mrace)
```

    ## # A tibble: 4 × 1
    ##   mrace
    ##   <dbl>
    ## 1     1
    ## 2     2
    ## 3     3
    ## 4     4

``` r
#Only 1, 2, 3, 4 for mrace

birth%>%
  distinct(malform)
```

    ## # A tibble: 2 × 1
    ##   malform
    ##     <dbl>
    ## 1       0
    ## 2       1

``` r
birth_cln<-birth%>%
  mutate( babysex = replace(babysex, babysex == 1, "Male"),
          babysex = replace(babysex, babysex == 2, "Female"), 
          frace = replace(frace, frace ==1, "White"),
          frace = replace(frace, frace ==2, "Black"),
          frace = replace(frace, frace ==3, "Asian"),
          frace = replace(frace, frace ==4, "Puerto Rican"),
          frace = replace(frace, frace ==8, "Other"),
          malform = replace(malform, malform ==0, "absent"), 
          malform = replace(malform, malform ==1, "present"),
          mrace = replace(mrace, mrace ==1, "White"),
          mrace = replace(mrace, mrace ==2, "Black"),
          mrace = replace(mrace, mrace ==3, "Asian"),
          mrace = replace(mrace, mrace ==4, "Puerto Rican"), 
          babysex = factor(babysex, levels=c("Male", "Female")), 
          frace = factor(frace, levels=c("White", "Black", "Asian", "Puerto Rican", "Other")),
          mrace = factor(mrace, levels=c("White", "Black", "Asian", "Puerto Rican")))

birth_cln%>%
  head(5)%>%
  knitr::kable()
```

| babysex | bhead | blength |  bwt | delwt | fincome | frace | gaweeks | malform | menarche | mheight | momage | mrace | parity | pnumlbw | pnumsga |    ppbmi | ppwt | smoken | wtgain |
|:--------|------:|--------:|-----:|------:|--------:|:------|--------:|:--------|---------:|--------:|-------:|:------|-------:|--------:|--------:|---------:|-----:|-------:|-------:|
| Female  |    34 |      51 | 3629 |   177 |      35 | White |    39.9 | absent  |       13 |      63 |     36 | White |      3 |       0 |       0 | 26.27184 |  148 |      0 |     29 |
| Male    |    34 |      48 | 3062 |   156 |      65 | Black |    25.9 | absent  |       14 |      65 |     25 | Black |      0 |       0 |       0 | 21.34485 |  128 |      0 |     28 |
| Female  |    36 |      50 | 3345 |   148 |      85 | White |    39.9 | absent  |       12 |      64 |     29 | White |      0 |       0 |       0 | 23.56517 |  137 |      1 |     11 |
| Male    |    34 |      52 | 3062 |   157 |      55 | White |    40.0 | absent  |       14 |      64 |     18 | White |      0 |       0 |       0 | 21.84508 |  127 |     10 |     30 |
| Female  |    34 |      52 | 3374 |   156 |       5 | White |    41.6 | absent  |       13 |      66 |     20 | White |      0 |       0 |       0 | 21.02642 |  130 |      1 |     26 |

Regression model for birthweight

From this [publication](https://pubmed.ncbi.nlm.nih.gov/7570074/), I
hypothesize that maternal race, infant sex, maternal smoking status, and
education would be important factors for birthweight. Since we do not
have education, I will use family monthly income (`fincome`) as a proxy
for education. Who defines smoking status as “someone who smokes a
tobacco product either daily or occasionally”. I will use `smoken` and
create a new variable `smoke_status` defined by smoker as greater than 0
cigrattes per day and non-smoker as 0 cigarettes per day.

``` r
#Create smoker variable 
birth_cln%>%
  distinct(smoken)
```

    ## # A tibble: 33 × 1
    ##    smoken
    ##     <dbl>
    ##  1  0    
    ##  2  1    
    ##  3 10    
    ##  4  4    
    ##  5  0.125
    ##  6 15    
    ##  7  8    
    ##  8  5    
    ##  9 20    
    ## 10  3    
    ## # … with 23 more rows

``` r
birth_cln<-birth_cln%>%
  mutate(smoke_status = case_when(smoken >0 ~ "smoker",
                                  smoken ==0 ~"non-smoker"))
```

Model Fitting Process - We will start with `smoke_status` and `babysex`
and evaluate based on Adjusted *R*<sup>2</sup>

``` r
fit = lm(bwt ~ smoke_status + babysex, data = birth_cln)
summary(fit)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ smoke_status + babysex, data = birth_cln)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -2583.82  -284.36    24.18   336.18  1676.53 
    ## 
    ## Coefficients:
    ##                    Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)         3207.82      12.68 252.902  < 2e-16 ***
    ## smoke_statussmoker  -116.46      15.65  -7.443 1.18e-13 ***
    ## babysexFemale        -93.35      15.41  -6.058 1.50e-09 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 507.1 on 4339 degrees of freedom
    ## Multiple R-squared:  0.02002,    Adjusted R-squared:  0.01957 
    ## F-statistic: 44.32 on 2 and 4339 DF,  p-value: < 2.2e-16

Let’s see if adding maternal race helps this model

``` r
fit_2 = lm(bwt ~ smoke_status + babysex + mrace, data = birth_cln)
summary(fit_2)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ smoke_status + babysex + mrace, data = birth_cln)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -2533.59  -268.12    21.08   309.88  1609.08 
    ## 
    ## Coefficients:
    ##                    Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)         3376.32      14.43 234.021  < 2e-16 ***
    ## smoke_statussmoker  -148.41      14.98  -9.909  < 2e-16 ***
    ## babysexFemale        -86.20      14.66  -5.881 4.37e-09 ***
    ## mraceBlack          -328.99      15.23 -21.600  < 2e-16 ***
    ## mraceAsian          -193.66      74.46  -2.601  0.00934 ** 
    ## mracePuerto Rican   -218.73      32.67  -6.696 2.41e-11 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 481.8 on 4336 degrees of freedom
    ## Multiple R-squared:  0.1159, Adjusted R-squared:  0.1149 
    ## F-statistic: 113.7 on 5 and 4336 DF,  p-value: < 2.2e-16

This slightly increased our Adjusted *R*<sup>2</sup> from 0.01957 to
0.1149. Let’s see if adding family monthly income helps (`fincome`).

``` r
fit_3 = lm(bwt ~ smoke_status + babysex + mrace+fincome, data = birth_cln)
summary(fit_3)
```

    ## 
    ## Call:
    ## lm(formula = bwt ~ smoke_status + babysex + mrace + fincome, 
    ##     data = birth_cln)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -2532.25  -270.33    19.36   311.50  1614.19 
    ## 
    ## Coefficients:
    ##                     Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)        3337.9871    22.4004 149.015  < 2e-16 ***
    ## smoke_statussmoker -146.9715    14.9834  -9.809  < 2e-16 ***
    ## babysexFemale       -85.7652    14.6514  -5.854 5.16e-09 ***
    ## mraceBlack         -314.3826    16.5673 -18.976  < 2e-16 ***
    ## mraceAsian         -185.8978    74.5113  -2.495   0.0126 *  
    ## mracePuerto Rican  -205.7811    33.1606  -6.206 5.96e-10 ***
    ## fincome               0.6870     0.3072   2.236   0.0254 *  
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 481.6 on 4335 degrees of freedom
    ## Multiple R-squared:  0.117,  Adjusted R-squared:  0.1157 
    ## F-statistic: 95.69 on 6 and 4335 DF,  p-value: < 2.2e-16

This slightly increased our Adjusted *R*<sup>2</sup> from 0.1149 to
0.1157. Still not the best model, this may suggest a linear model is not
the best fit for birthweight. However, we will continue using `fit_3`.

Compare your model to two others:

One using length at birth and gestational age as predictors (main
effects only) One using head circumference, length, sex, and all
interactions (including the three-way interaction) between these

## Problem 2

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## Registered S3 method overwritten by 'hoardr':
    ##   method           from
    ##   print.cache_info httr

    ## using cached file: ~/Library/Caches/R/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2021-10-05 09:30:21 (7.602)

    ## file min/max dates: 1869-01-01 / 2021-10-31
